spring:
  datasource: # url后面加的这个rewriteBatchedStatements=true即开启，开启后允许 JDBC 将多个插入/更新语句合并成一个批次发送，提高批量操作性能
    url: jdbc:mysql://127.0.0.1:3306/mp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
logging:
  level:
    xyz.sonyp.mapper: trace  # 跟踪 Mapper 接口代理过程
    xyz.songyp: debug
  pattern:
    dateformat: HH:mm:ss
# MyBatisPlus配置继承了Mybatis原生配置和一些自己特有的配置
mybatis-plus: # mabatisPlus更擅长的是 单表的增删改查
  type-aliases-package: xyz.sonyp.po # 别名扫描包
  mapper-locations: classpath*:/mapper/**/*.xml # Mapper.xml文件地址，默认值(mp擅长单表，因此mp允许额外使用mybatis)
  configuration:
    map-underscore-to-camel-case: true # 是否开启下划线和驼峰的映射
    cache-enabled: false # 是否开启二进制缓存
  global-config:
    db-config:
      id-type: assign_id # id为雪花算法生成（默认id为主键）
      update-strategy: not_null # 更新策略：只更新非空字段
